[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "Lekton Nerd Font"
style = "Bold"

[terminal.shell]
program = "wsl.exe"

[window]
startup_mode = "Maximized"
decorations = "full"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
